// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdm6WTOYXnfosV4j3zyoYR7HeiAuCvCsk',
    appId: '1:36060505058:web:fcd0633bf67dd32bda0fbb',
    messagingSenderId: '36060505058',
    projectId: 'ecommerce-app-cfdbb',
    authDomain: 'ecommerce-app-cfdbb.firebaseapp.com',
    storageBucket: 'ecommerce-app-cfdbb.appspot.com',
    measurementId: 'G-XW9NVT5JST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56-nw5hJgh15fqSa8ml7gQLLaWWO299o',
    appId: '1:36060505058:android:dbdef39840a91a68da0fbb',
    messagingSenderId: '36060505058',
    projectId: 'ecommerce-app-cfdbb',
    storageBucket: 'ecommerce-app-cfdbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSCXxT3Ld8MGq0nbs0NCkPwMA9RXz90DY',
    appId: '1:36060505058:ios:04946c3f7d245b79da0fbb',
    messagingSenderId: '36060505058',
    projectId: 'ecommerce-app-cfdbb',
    storageBucket: 'ecommerce-app-cfdbb.appspot.com',
    androidClientId: '36060505058-8d4nt0bs8fp1qh74ef9573l2kc61skcd.apps.googleusercontent.com',
    iosClientId: '36060505058-u210l9as1fek5hhdlb71e627gc2iqhm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSCXxT3Ld8MGq0nbs0NCkPwMA9RXz90DY',
    appId: '1:36060505058:ios:04946c3f7d245b79da0fbb',
    messagingSenderId: '36060505058',
    projectId: 'ecommerce-app-cfdbb',
    storageBucket: 'ecommerce-app-cfdbb.appspot.com',
    androidClientId: '36060505058-8d4nt0bs8fp1qh74ef9573l2kc61skcd.apps.googleusercontent.com',
    iosClientId: '36060505058-u210l9as1fek5hhdlb71e627gc2iqhm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiStore',
  );
}
